const nodemailer = require('nodemailer');

module.exports = async (req, res) => {
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
    if (req.method === 'OPTIONS') return res.status(200).end();
    if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });

    const { toEmail, reportHtml } = req.body;
    if (!toEmail || !reportHtml) {
        return res.status(400).json({ error: 'Missing required fields' });
    }

    const fullHtml = `
        <!DOCTYPE html>
        <html>
        <head><meta charset="UTF-8"><title>NetEye Security Report</title></head>
        <body style="font-family: sans-serif; max-width: 800px; margin: 0 auto;">
            <h1>NetEye Security Scan Report</h1>
            <div>${reportHtml}</div>
            <hr />
            <p style="font-size: 12px; color: #666;">
                ⚠️ This report is for authorized security testing only. Unauthorized scanning is prohibited.<br />
                Generated by <a href="https://neteye.vercel.app">NetEye Scanner</a> | Contact: zero6039@gmail.com
            </p>
        </body>
        </html>
    `;

    // 配置 SMTP 传输（使用 Gmail）
    const transporter = nodemailer.createTransport({
        service: 'gmail',
        auth: {
            user: 'zero6039@gmail.com',          // 您的 Gmail 地址
            pass: awftwtzfpvhmbtqg // 应用专用密码（环境变量）
        }
    });

    const mailOptions = {
        from: 'zero6039@gmail.com',
        to: toEmail,
        subject: 'NetEye Security Report',
        html: fullHtml,
        attachments: [
            {
                filename: 'security_report.html',
                content: fullHtml,
                contentType: 'text/html'
            }
        ]
    };

    try {
        await transporter.sendMail(mailOptions);
        res.json({ success: true });
    } catch (error) {
        console.error(error);
        res.status(500).json({ error: 'Failed to send email' });
    }
};
