const sgMail = require('@sendgrid/mail');

// 从环境变量获取 SendGrid API Key
sgMail.setApiKey(process.env.SENDGRID_API_KEY);

module.exports = async (req, res) => {
    // 设置 CORS 头，允许前端跨域请求
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
    if (req.method === 'OPTIONS') return res.status(200).end();
    if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });

    const { toEmail, reportHtml } = req.body;
    if (!toEmail || !reportHtml) {
        return res.status(400).json({ error: 'Missing required fields' });
    }

    // 构造完整的邮件 HTML（包含免责声明和联系信息）
    const fullHtml = `
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="UTF-8">
            <title>NetEye Security Report</title>
            <style>
                body { font-family: sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; }
                .footer { margin-top: 30px; padding: 10px; border-top: 1px solid #ccc; font-size: 12px; color: #666; text-align: center; }
            </style>
        </head>
        <body>
            <h1>NetEye Security Scan Report</h1>
            <div>${reportHtml}</div>
            <div class="footer">
                <p>⚠️ This report is for authorized security testing only. Unauthorized scanning is prohibited.</p>
                <p>Report generated by <a href="https://neteye.vercel.app">NetEye Scanner</a> | Contact: zero6039@gmail.com</p>
            </div>
        </body>
        </html>
    `;

    const msg = {
        to: toEmail,
        from: 'zero6039@gmail.com', // 必须在 SendGrid 中验证的发件人邮箱
        subject: 'NetEye Security Report',
        html: fullHtml,
        attachments: [
            {
                content: Buffer.from(fullHtml).toString('base64'),
                filename: 'security_report.html',
                type: 'text/html',
                disposition: 'attachment'
            }
        ]
    };

    try {
        await sgMail.send(msg);
        res.json({ success: true });
    } catch (error) {
        console.error('SendGrid error:', error);
        res.status(500).json({ error: 'Failed to send email' });
    }
};
